title: Racing Simulation
description: Documentation for Racing Simulation
baseurl: "/formula_student_sim_client"
url: "https://your-username.github.io"  # Replace with your GitHub username
markdown: kramdown
plugins:
  - jekyll-feed
